<a href="https://colab.research.google.com/github/AlexandreMachineLearning/Classificacao-KNN/blob/main/Q_4_Classificacao_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Usando 10-fold cross validation, use um modelo KNN (k = 15, distancia euclidiana), para descobrir a acurácia média de validação dos dados em classificacao_Q4.csv

Passo 1 - Importação das bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Passo 2 - Criação e Carregamento do dataframe

In [2]:
classificacao_knn_df=pd.read_csv('/content/classificacao_Q4.csv')

In [3]:
classificacao_knn_df

x0        x1        x2  ...       x98       x99  target
0     1.696199 -0.792598 -0.349427  ... -0.309441 -1.549833     4.0
1    -0.236696 -2.202342  0.024023  ... -0.354139  0.806797     5.0
2    -0.436683  1.563816 -0.895999  ...  1.304518  0.478903     3.0
3     1.425908  0.400055 -0.305038  ... -1.927319  1.959032     8.0
4    -0.186156 -0.975764  0.594660  ... -0.218596  0.619317     9.0
...        ...       ...       ...  ...       ...       ...     ...
1495  1.080739  0.783280 -0.161391  ...  0.211155 -0.902594     9.0
1496 -0.308847 -0.730387 -0.147572  ...  0.264665 -0.486857     9.0
1497  1.115912  0.640986  0.588652  ... -2.982769 -1.140083     4.0
1498 -0.699961  0.633079  0.235042  ... -1.332670  0.826682     3.0
1499  0.280078  1.516305  0.291862  ...  0.509123 -2.359495     1.0

[1500 rows x 101 columns]

In [4]:
classificacao_knn_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Columns: 101 entries, x0 to target
dtypes: float64(101)
memory usage: 1.2 MB


Passo 3 - Separação dos dados

In [5]:
X_classificacao_knn=classificacao_knn_df.iloc[:,0:100].values

In [6]:
X_classificacao_knn

array([[ 1.69619932, -0.79259839, -0.34942688, ...,  1.1584772 ,
        -0.30944077, -1.54983294],
       [-0.23669567, -2.20234229,  0.02402259, ...,  1.25956623,
        -0.35413861,  0.80679689],
       [-0.4366833 ,  1.56381643, -0.89599888, ...,  1.72148724,
         1.30451814,  0.4789029 ],
       ...,
       [ 1.11591217,  0.64098565,  0.58865231, ...,  0.40841819,
        -2.98276921, -1.14008314],
       [-0.69996088,  0.63307874,  0.23504182, ...,  3.42615957,
        -1.33266967,  0.82668242],
       [ 0.28007765,  1.51630479,  0.29186232, ..., -0.69872584,
         0.50912253, -2.35949479]])

In [7]:
y_classificacao_knn=classificacao_knn_df.iloc[:,100].values

In [8]:
y_classificacao_knn

array([4., 5., 3., ..., 4., 3., 1.])

Passo 4 - Separação dos dados de treinamento e teste

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
from sklearn.model_selection import cross_val_score

In [11]:
X_knn_treinamento, X_knn_teste, y_knn_treinamento, y_knn_teste = train_test_split(X_classificacao_knn, y_classificacao_knn, test_size = 0.30)

In [12]:
X_knn_treinamento.shape, y_knn_treinamento.shape

((1050, 100), (1050,))

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
knn_classificacao=KNeighborsClassifier(n_neighbors=15,metric='minkowski',p=2)

In [15]:
knn_classificacao.fit(X_knn_treinamento,y_knn_treinamento)

KNeighborsClassifier(n_neighbors=15)

Passo 5 - Previsões

In [16]:
previsoes=knn_classificacao.predict(X_knn_teste)

In [17]:
previsoes

array([7., 4., 0., 9., 4., 1., 0., 0., 9., 7., 1., 0., 3., 3., 6., 7., 6.,
       1., 1., 6., 6., 2., 2., 0., 1., 8., 5., 9., 6., 6., 8., 5., 1., 8.,
       9., 4., 9., 2., 9., 8., 7., 4., 2., 2., 3., 3., 5., 9., 8., 9., 5.,
       0., 7., 0., 9., 5., 7., 4., 2., 6., 3., 2., 4., 4., 8., 0., 7., 1.,
       4., 3., 3., 9., 1., 8., 7., 9., 5., 6., 0., 2., 3., 6., 8., 9., 8.,
       9., 8., 0., 8., 9., 8., 1., 6., 8., 2., 6., 1., 2., 7., 1., 1., 4.,
       6., 8., 4., 1., 1., 3., 0., 6., 9., 6., 8., 8., 2., 6., 1., 2., 6.,
       2., 2., 5., 1., 4., 4., 8., 1., 8., 1., 8., 2., 1., 3., 0., 5., 1.,
       4., 8., 8., 1., 9., 1., 3., 7., 7., 3., 1., 8., 6., 7., 5., 6., 4.,
       0., 1., 9., 1., 4., 6., 7., 7., 3., 7., 8., 9., 6., 6., 4., 1., 3.,
       3., 9., 7., 9., 7., 5., 0., 5., 0., 0., 1., 6., 1., 4., 9., 1., 9.,
       0., 1., 7., 0., 9., 3., 3., 7., 8., 8., 6., 8., 9., 9., 9., 3., 8.,
       8., 0., 3., 9., 4., 1., 8., 1., 2., 3., 6., 2., 9., 2., 8., 6., 6.,
       7., 1., 1., 5., 0.

In [18]:
y_knn_teste

array([7., 4., 7., 9., 2., 3., 0., 0., 4., 7., 2., 0., 3., 9., 5., 7., 6.,
       3., 2., 6., 6., 2., 2., 0., 9., 8., 5., 9., 6., 6., 7., 5., 1., 8.,
       9., 1., 9., 2., 9., 5., 0., 9., 2., 6., 3., 4., 5., 9., 0., 4., 0.,
       0., 5., 7., 9., 5., 7., 4., 0., 8., 4., 2., 4., 9., 6., 4., 7., 1.,
       3., 3., 3., 9., 6., 1., 5., 9., 7., 6., 2., 2., 3., 1., 2., 9., 8.,
       9., 8., 0., 2., 9., 8., 7., 1., 0., 2., 7., 2., 2., 3., 1., 2., 4.,
       8., 8., 4., 1., 1., 4., 0., 6., 9., 6., 8., 7., 2., 2., 1., 2., 6.,
       5., 3., 5., 4., 4., 4., 8., 5., 8., 5., 8., 2., 1., 4., 5., 0., 4.,
       4., 8., 8., 1., 9., 3., 3., 7., 7., 3., 5., 5., 6., 7., 5., 2., 4.,
       0., 1., 9., 2., 1., 6., 7., 7., 3., 7., 6., 9., 6., 5., 4., 1., 9.,
       4., 1., 7., 9., 7., 0., 0., 5., 0., 0., 4., 1., 1., 4., 9., 1., 4.,
       0., 1., 7., 5., 9., 3., 3., 7., 8., 2., 8., 8., 2., 7., 9., 3., 8.,
       8., 0., 3., 9., 4., 1., 5., 1., 2., 3., 5., 2., 5., 2., 8., 6., 7.,
       5., 1., 1., 5., 0.

In [19]:
from sklearn.metrics import accuracy_score, classification_report


In [20]:
accuracy_score(y_knn_teste,previsoes)

0.6555555555555556

Passo 6 - Criando o Cross Validation

In [21]:
scores= cross_val_score(knn_classificacao,X_classificacao_knn,y_classificacao_knn,cv=10,scoring='accuracy')

In [22]:
scores

array([0.68666667, 0.62      , 0.64666667, 0.66666667, 0.64666667,
       0.64      , 0.65333333, 0.68      , 0.70666667, 0.60666667])

Passo 7 - Média dos resultados

In [23]:
scores.mean()

0.6553333333333333